"""Bancos de fragmentos por grupo de lugar y por familia de empuje."""

# {lugar} = nombre del tipo (Oficina). Clases: sensorial, ambiente, fragmento, reaccion, perfil.

GRUPO = {
    "trabajo": {
        "sensorial": [
            "El fluorescente zumba un tono más alto de lo que debería.",
            "Huele a tóner, café frío y alfombra de hace años.",
            "El teclado de alguien, lejos, no para.",
            "La luz no tiene sombra: todo queda plano.",
            "El aire acondicionado pega en la nuca.",
            "Hay un olor a plástico caliente de máquina.",
            "El alfombrado traga los pasos y no los secretos.",
            "Un sello, un beep, un cajón que no cierra.",
            "El reloj de pared adelanta medio minuto y nadie lo corrige.",
            "Huele a piso encerado a destiempo.",
            "La impresora parpadea un error que nadie lee.",
            "Un café de máquina quema la lengua y no consuela.",
        ],
        "ambiente": [
            "Los cubículos recortan el aire en cajas iguales.",
            "Hay un silencio de gente que finge trabajar.",
            "El horario pesa más que la voluntad.",
            "Se oye todo y se finge que no.",
            "La jerarquía se sienta en sillas distintas.",
            "El día se parece al de ayer hasta en los ruidos.",
            "Nadie se queda de más sin un motivo.",
            "El pasillo es más estrecho de lo que admite.",
        ],
        "fragmento": [
            "Una taza con el logo de la empresa, vacía.",
            "Un expediente cerrado, a propósito, en el borde.",
            "Cables por el suelo; nadie los recogerá.",
            "La silla de ruedas de oficina chirría al girar.",
            "Un post-it de otro turno, ya sin sentido.",
            "La planta de plástico, siempre igual de viva.",
            "El gafete contra el pecho, de más.",
            "Una pizarra con un diagrama que ya no se usa.",
        ],
    },
    "casa": {
        "sensorial": [
            "El olor de siempre, un grado más fuerte.",
            "La madera del piso denuncia cada paso.",
            "Huele a comida de hace horas, o a jabón.",
            "La canilla gotea un tiempo que no es el del reloj.",
            "La luz del velador no llega a las esquinas.",
            "Un electrodoméstico zumba como si fuera gente.",
            "Las sábanas tienen el calor de quien se fue o de quien sigue.",
            "Huele a humedad de toalla que no seca.",
        ],
        "ambiente": [
            "Los objetos están donde los dejaste, o no.",
            "Las paredes son delgadas para lo que se va a decir.",
            "El adentro mira el afuera; a veces al revés.",
            "Nadie es del todo de visita y nadie es del todo dueño.",
            "La casa pide formas: zapatos, voz, horarios.",
            "Lo íntimo cabe en un cajón y también lo otro.",
        ],
        "fragmento": [
            "Una taza en el fregadero, de ayer.",
            "La llave en la cerradura, a medias.",
            "Un felpudo que ya no dice bienvenido.",
            "La tele encendida para nadie.",
            "Un zapato solo, debajo de la cama.",
            "La ventana entreabierta a un patio ajeno.",
        ],
    },
    "transito": {
        "sensorial": [
            "El asfalto todavía suelta calor.",
            "Huele a escape, a lluvia, a gente apurada.",
            "El vidrio empañado recorta caras ajenas.",
            "El metal del caño está frío o demasiado usado.",
            "Un anuncio habla y nadie escucha del todo.",
            "El vaivén entra en el estómago.",
            "Luces en fila; no hay costado.",
            "El viento de la velocidad desarma el pelo y el plan.",
        ],
        "ambiente": [
            "Gente que no se detiene.",
            "Nadie es del todo de nadie.",
            "El cruce es una decisión.",
            "Se comparte el aire y no el destino.",
            "El reloj de la estación miente o adelanta.",
            "Ir de un sitio a otro ya es la escena.",
        ],
        "fragmento": [
            "Un boleto usado, todavía tibio.",
            "La maleta que no es tuya, demasiado cerca.",
            "El semáforo en rojo junta a quienes no se eligieron.",
            "Un asiento vacío que nadie toma.",
            "El espejo retrovisor, más honesto que la boca.",
            "Una parada, un cartel, gente que finge no verse.",
        ],
    },
    "comida": {
        "sensorial": [
            "El vaso deja un círculo húmedo en la madera.",
            "Huele a aceite, a cebolla, a alcohol barato o caro.",
            "Las voces se pisan; nadie oye del todo.",
            "El hielo golpea el vaso con un ritmo de más.",
            "La luz de la barra recorta bocas y no intenciones.",
            "Huele a café que ya no está caliente.",
            "El plato llega con un vapor que dura poco.",
            "Hay un olor a fritura que se pega a la ropa.",
        ],
        "ambiente": [
            "Hay testigos, o se finge que no.",
            "La mesa es un pretexto para quedarse.",
            "Se habla a medio volumen para que el de al lado no oiga, y oye.",
            "El cantinero oye y no oye.",
            "La alegría, si hay, es un poco obligatoria.",
            "Pagar es la única salida clara.",
        ],
        "fragmento": [
            "Una silla coja junto a la barra.",
            "El cenicero lleno de otra noche.",
            "Un cubierto torcido, a propósito o no.",
            "La servilleta escrita y doblada.",
            "La copa que no es la primera.",
            "El menú sucio de huellas.",
        ],
    },
    "salud": {
        "sensorial": [
            "Huele a alcohol y a piso que no termina de secar.",
            "La luz es de más para lo que se va a decir.",
            "Un aparato pita lejos, sin prisa y con prisa.",
            "El papel del camastro cruje al sentarse.",
            "Huele a miedo disfrazado de limpio.",
            "El pasillo alarga los pasos de goma.",
        ],
        "ambiente": [
            "El cuerpo entra en tercera persona.",
            "El nombre que llaman no es el tuyo, todavía.",
            "Se espera como oficio.",
            "Nadie eligió la hora.",
            "La bata iguala y no consuela.",
        ],
        "fragmento": [
            "Una revista de otro año.",
            "El botón de llamado, a un palmo.",
            "El tensiómetro, más íntimo que la charla.",
            "Un número en vez del nombre.",
            "La silla de espera, demasiado fija.",
        ],
    },
    "civico": {
        "sensorial": [
            "Huele a papel, a piso encerado, a cola humana.",
            "El sello golpea con un ruido más grave que la frase.",
            "La ventanilla recorta caras.",
            "El eco del mármol o del hormigón no perdona.",
            "Un número de turno, más alto que el ánimo.",
        ],
        "ambiente": [
            "La forma pesa más que el hecho.",
            "El cuerpo aprende a esperar.",
            "Se es un trámite con zapatos.",
            "El poder tiene alfombra, o silla de plástico.",
            "Nadie es de acá; todos tienen un papel.",
        ],
        "fragmento": [
            "El ticket húmedo de tanto apretarlo.",
            "Un formulario con un renglón de más.",
            "La lapicera atada al mostrador.",
            "El banco de espera, pulido de tanto uso.",
            "Un cartel que nadie lee y todos obedecen.",
        ],
    },
    "sagrado": {
        "sensorial": [
            "El eco es más grande que la voz.",
            "Huele a cera, a humedad de piedra, a flores de más.",
            "La madera del banco está pulida de rodillas ajenas.",
            "Una llama chica mueve todas las sombras.",
            "El silencio pide forma.",
        ],
        "ambiente": [
            "Hay algo que no se toca.",
            "El umbral cambia las reglas.",
            "Se entra distinto de como se está en la calle.",
            "El rito ordena hasta a quien no cree.",
        ],
        "fragmento": [
            "Una ofrenda que ya no es de nadie.",
            "El agua en una pila, demasiado quieta.",
            "Un banco vacío en la primera fila.",
            "La puerta, más pesada al salir.",
        ],
    },
    "naturaleza": {
        "sensorial": [
            "El viento trae un olor que no es de ciudad.",
            "Bajo los pies, algo vivo o algo podrido.",
            "El oído trabaja más que la vista.",
            "La luz llega filtrada, o de más.",
            "Hay frío de sombra y calor de claro, a un paso.",
            "Un insecto insiste cerca de la oreja.",
        ],
        "ambiente": [
            "Poco control, mucho oído.",
            "El mapa no está, o miente.",
            "El horizonte pesa.",
            "Nadie manda del todo, ni vos.",
        ],
        "fragmento": [
            "Una rama quebrada a propósito o no.",
            "Huellas que no son las tuyas.",
            "El agua, más oscura de cerca.",
            "Un banco de plaza con una dedicación ilegible.",
        ],
    },
    "ocio": {
        "sensorial": [
            "La oscuridad pactada recorta la cara a ratos.",
            "Huele a palomitas, a cloro, a esfuerzo, a alfombra.",
            "Un grito ajenos se vuelve tuyo un segundo.",
            "La luz de escenario no es para vos, y te da igual.",
            "El eco de la masa entra en el pecho.",
        ],
        "ambiente": [
            "Se paga para sentir otra cosa.",
            "El cuerpo es exhibición o escondite.",
            "Las reglas del juego no son las de afuera.",
            "Vos sos un punto, o el punto.",
        ],
        "fragmento": [
            "La butaca que cruje en el momento malo.",
            "Un vaso de plástico, ya sin hielo.",
            "El marcador, más honesto que la gente.",
            "El casillero que no cierra del todo.",
        ],
    },
    "intimidad": {
        "sensorial": [
            "Las sábanas no huelen a vos, o huelen demasiado.",
            "La luz de la lámpara deja un lado de la cara.",
            "El aire está más corto entre una frase y la siguiente.",
            "Un roce de tela; nada más, y basta.",
            "La ciudad entra por la cortina, apagada.",
            "Huele a jabón de hotel, a piel, a minibar.",
        ],
        "ambiente": [
            "Pocas personas, poca ropa de rol.",
            "El tablero es más chico y más grave.",
            "Nadie es de ahí, o eso se finge.",
            "La puerta con traba es el único pacto claro.",
        ],
        "fragmento": [
            "El espejo, demasiado honesto.",
            "Un reloj que se paga por hora.",
            "La silla con la ropa en el orden de haberse quitado.",
            "El vaso en la mesa de luz, a medio.",
        ],
    },
    "comercio": {
        "sensorial": [
            "La luz de góndola no perdona la cara.",
            "Huele a nuevo, a plástico, a perfume de tester.",
            "El beep de la caja marca un tiempo ajeno.",
            "El vidrio de la vidriera te devuelve distinto.",
            "Hay un olor a ropa de otro, o a metal de cajón.",
        ],
        "ambiente": [
            "Se mide a quien entra.",
            "El objeto vale más que el gesto, o al revés.",
            "La cola en la nuca apura sin hablar.",
            "Todo tiene número.",
        ],
        "fragmento": [
            "La percha vacía, todavía balanceándose.",
            "El ticket largo, inútil en un minuto.",
            "El probador, una cortina como umbral.",
            "El precio, más visible que la persona.",
        ],
    },
    "reclusion": {
        "sensorial": [
            "El metal está más frío que el trato.",
            "Huele a piso, a cuerpo, a tiempo encerrado.",
            "La luz no se apaga cuando debería.",
            "El eco de la reja es más claro que la voz.",
            "Poco aire; el afuera es teoría.",
        ],
        "ambiente": [
            "El tiempo es el castigo, o es todo lo que hay.",
            "Ser visto es el punto, o no serlo.",
            "El cuerpo ya no es del todo tuyo.",
            "Las reglas no se discuten: se habitan.",
        ],
        "fragmento": [
            "La ranura de la puerta, a la altura de los ojos.",
            "Un banco de metal, demasiado estrecho.",
            "El cielo recortado en un rectángulo.",
            "La litera de arriba, más cerca del techo que de vos.",
        ],
    },
    "infra": {
        "sensorial": [
            "Faroles naranjas, hormigón, un eco que no es de gente.",
            "Huele a humedad de caño, a nafta, a polvo de obra.",
            "El zumbido no es para vos y no se apaga.",
            "Luces en fila; no hay costado.",
            "El control remoto, o la llave, como único permiso.",
        ],
        "ambiente": [
            "Nadie debería estar tanto.",
            "El detrás de la ciudad no tiene cara.",
            "El peligro a veces está escrito.",
            "Es un atajo, o una trampa, o las dos.",
        ],
        "fragmento": [
            "Un pilar numerado, más testigo que la cámara.",
            "La grava bajo los zapatos.",
            "Un medidor que gira sin que lo mires.",
            "La escalera de emergencia, más limpia de lo que debería.",
        ],
    },
}

FAMILIA = {
    "cotidiano": [
        ("ambiente", "Nada “pasa” y aun así todo pesa."),
        ("fragmento", "Un trámite, un café, una frase de más."),
        ("sensorial", "El mismo zumbido, el mismo café."),
        ("reaccion", "Se responde con el tono de siempre."),
        ("ambiente", "El reloj manda más que la gana."),
        ("fragmento", "La misma mancha en el techo."),
    ],
    "afecto": [
        ("ambiente", "El vínculo es el motor, no el decorado."),
        ("reaccion", "Se le nota el pulso en la garganta cuando traga."),
        ("reaccion", "Sonríe de lado, como si no quisiera que se viera."),
        ("fragmento", "Una mano que no termina de posarse."),
        ("sensorial", "La distancia entre dos cuerpos se nota como un tercer personaje."),
        ("ambiente", "Nadie mira a los demás; se miran ellos."),
    ],
    "deseo": [
        ("ambiente", "El cuerpo ocupa más sitio que la conversación."),
        ("sensorial", "Un roce de tela; nada más, y basta."),
        ("reaccion", "Se le va la mirada a la boca."),
        ("reaccion", "Se le nota la respiración un poco alta."),
        ("fragmento", "Un botón, un borde de tela, nada más."),
        ("ambiente", "Se podría tocar y no se toca, o sí."),
    ],
    "miedo": [
        ("ambiente", "El espacio no te da sitio."),
        ("reaccion", "Los hombros no bajan."),
        ("sensorial", "El techo parece más bajo de lo que es."),
        ("ambiente", "Algo puede hacer daño y está cerca."),
        ("fragmento", "La salida, más lejos de lo que era."),
        ("reaccion", "Nadie cede el paso."),
    ],
    "poder": [
        ("ambiente", "Se nota quién se sienta dónde."),
        ("reaccion", "Interrumpe sin disculparse."),
        ("fragmento", "Dos sillas; una más baja."),
        ("ambiente", "El estatus se puede romper en un gesto pequeño."),
        ("reaccion", "Asiente sin mirar."),
        ("sensorial", "La voz correcta; el resto no."),
    ],
    "verdad": [
        ("ambiente", "Falta una pieza a la vista y todos lo saben."),
        ("fragmento", "Un cajón entreabierto que no debería estarlo."),
        ("reaccion", "La sonrisa se queda a medias."),
        ("ambiente", "Se dice lo que se callaba, o se calla más."),
        ("sensorial", "El silencio dura un segundo de más."),
        ("fragmento", "Un papel, un mail, una prueba chica."),
    ],
    "moral": [
        ("ambiente", "Hay que elegir, y duele cualquiera de las dos."),
        ("reaccion", "Se le va la mirada al piso."),
        ("fragmento", "Una deuda que no es de dinero."),
        ("ambiente", "El pasado no se queda en el pasado."),
        ("reaccion", "Traga saliva como quien traga una frase."),
        ("sensorial", "El aire pesa a culpa, o a alivio, o a las dos."),
    ],
    "tiempo": [
        ("ambiente", "Si no es ahora, no es."),
        ("sensorial", "El reloj marca un minuto que ya conocías."),
        ("fragmento", "Una fecha, un plazo, el cuello."),
        ("reaccion", "Mira el reloj y no es por la hora."),
        ("ambiente", "El después tarda más que el cuerpo."),
        ("fragmento", "El mismo nudo, otra vez."),
    ],
    "cuerpo": [
        ("sensorial", "El cuerpo pide y no entiende de relatos."),
        ("reaccion", "Los párpados pesan más que la escena."),
        ("ambiente", "El cuerpo manda sobre la agenda."),
        ("fragmento", "Sudor, o frío, o las dos en la misma camisa."),
        ("sensorial", "Duele, y eso ordena."),
        ("reaccion", "Se acomoda la ropa como quien se acomoda el ánimo."),
    ],
    "sagrado": [
        ("ambiente", "Hay algo que no se toca."),
        ("sensorial", "El eco pide forma."),
        ("fragmento", "Un gesto chico, como ofrenda o como miedo."),
        ("ambiente", "Pasar de un lado al otro cambia las reglas."),
        ("reaccion", "Baja la voz aunque no haga falta."),
        ("fragmento", "Lo intocable, a un palmo."),
    ],
    "comic": [
        ("ambiente", "El roce social se vuelve absurdo."),
        ("reaccion", "Se ríe en el momento malo, o no se ríe en el bueno."),
        ("fragmento", "Un chiste que es un golpe."),
        ("ambiente", "Nadie cree del todo y aun así representan."),
        ("sensorial", "Hay de más: luz, voz, exceso."),
        ("reaccion", "La cara no sabe si es risa o vergüenza."),
    ],
    "fatal": [
        ("ambiente", "El fallo es irreversible, o se siente así."),
        ("reaccion", "Se queda un segundo de más en lo que ya no está."),
        ("fragmento", "Lo que se va y no vuelve igual."),
        ("ambiente", "Iba a pasar, y pasa."),
        ("sensorial", "El aire tiene un peso de final."),
        ("reaccion", "No hay plan B en la cara."),
    ],
    "bando": [
        ("ambiente", "Se elige un nosotros contra un ellos."),
        ("reaccion", "Mira de reojo a quién está de qué lado."),
        ("fragmento", "Una lealtad que se nota en el asiento."),
        ("ambiente", "El espacio ya no es de quienes lo habitaban."),
        ("sensorial", "El ruido de más de un grupo, no de personas."),
        ("reaccion", "Se pone a un lado sin preguntar, o al otro."),
    ],
}

# plantillas de cruce: familia x lugar. {lugar} = nombre.
CRUCE = {
    "cotidiano": [
        "En {lugar}, el reloj manda más que lo que se vino a hacer.",
        "{lugar} se parece a ayer hasta en los ruidos.",
        "Nada pasa en {lugar} y aun así todo pesa.",
    ],
    "afecto": [
        "En {lugar} la distancia entre dos cuerpos se vuelve el tema.",
        "{lugar} de pronto es solo el fondo de una mirada.",
        "Se podría descansar en {lugar}, si el otro dejara.",
    ],
    "deseo": [
        "El cuerpo ocupa más sitio que {lugar}, y {lugar} no estaba hecho para eso.",
        "En {lugar} un roce vale más que el diálogo.",
        "{lugar} presta la luz justa para ver de más.",
    ],
    "miedo": [
        "{lugar} de pronto parece no tener salida.",
        "En {lugar} un ruido de más adelanta al cuerpo.",
        "El techo de {lugar} parece más bajo de lo que es.",
    ],
    "poder": [
        "En {lugar} se nota quién se sienta dónde.",
        "{lugar} tiene sillas distintas para el mismo aire.",
        "El estatus se puede romper aquí, en {lugar}, con un gesto.",
    ],
    "verdad": [
        "En {lugar} falta una pieza a la vista.",
        "{lugar} guarda un cajón que no debería estar así.",
        "El silencio de {lugar} dura un segundo de más.",
    ],
    "moral": [
        "En {lugar} hay que elegir, y duele cualquiera de las dos.",
        "{lugar} no absuelve; solo presencia.",
        "El pasado cabe en {lugar} mejor que el presente.",
    ],
    "tiempo": [
        "Si no es ahora, {lugar} no va a esperar.",
        "El reloj de {lugar} marca un minuto que ya conocías.",
        "En {lugar} el después tarda más que el cuerpo.",
    ],
    "cuerpo": [
        "En {lugar} el cuerpo pide y no entiende de relatos.",
        "{lugar} huele a gente, a cansancio, a lo que no se dice.",
        "El cuerpo manda aquí, en {lugar}, sobre la agenda.",
    ],
    "sagrado": [
        "En {lugar} hay algo que no se toca, o se toca igual.",
        "{lugar} cambia las reglas al cruzar el umbral.",
        "Se baja la voz en {lugar} aunque no haga falta.",
    ],
    "comic": [
        "En {lugar} el roce se vuelve absurdo y se sigue.",
        "{lugar} no estaba pensado para este ridículo, y por eso.",
        "Da risa, en {lugar}, porque no se puede salir.",
    ],
    "fatal": [
        "En {lugar} se siente que esto no se deshace.",
        "{lugar} presencia un final que todavía no se nombra.",
        "El aire de {lugar} tiene peso de lo que se va.",
    ],
    "bando": [
        "En {lugar} se elige un nosotros contra un ellos.",
        "{lugar} ya no es de quienes lo habitaban del todo.",
        "Se nota el lado, en {lugar}, por el asiento.",
    ],
}

PERSONAJE = [
    ("perfil", "Se le nota el oficio en el modo de ocupar el espacio."),
    ("reaccion", "Te mira de reojo antes de contestar."),
    ("reaccion", "Baja la voz aunque no haga falta."),
    ("perfil", "Habla como quien comparte el mismo aire todos los días, o como quien no."),
    ("reaccion", "Asiente sin mirar, o mira sin asentir."),
    ("fragmento", "Un gesto pequeño, de quien ya estuvo aquí."),
    ("perfil", "Cambia de tono según quién entra."),
    ("reaccion", "Se queda un segundo de más en lo que ve."),
]
